# Generated by Django 2.1.5 on 2019-02-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='code_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
