# Generated by Django 2.1.5 on 2019-02-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20190213_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='code_created',
            field=models.DateTimeField(null=True),
        ),
    ]
