# Generated by Django 2.1.5 on 2019-02-19 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('todo', '0008_auto_20190213_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlpacaAPIKeys',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('key_id', fernet_fields.fields.EncryptedTextField()),
                ('secret_key', fernet_fields.fields.EncryptedTextField()),
            ],
        ),
    ]
