# Generated by Django 2.1.5 on 2019-02-20 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20190220_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alpacaapikeys',
            old_name='user_id',
            new_name='user',
        ),
    ]
