# Generated by Django 2.1.5 on 2019-02-21 21:29

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20190220_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alpacaapikeys',
            name='secret_key',
            field=fernet_fields.fields.EncryptedTextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
