# Generated by Django 2.1.5 on 2019-02-10 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import marco_polo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marco_polo', '0002_useravatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstlogin', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=6)),
                ('code_created', models.DateField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=marco_polo.models.get_image_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='useravatar',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAvatar',
        ),
    ]
