# Generated by Django 2.1.5 on 2019-02-26 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0012_auto_20190221_2129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
