# Generated by Django 2.1.5 on 2019-02-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0013_delete_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alpacaapikeys',
            name='user',
        ),
        migrations.AddField(
            model_name='alpacaapikeys',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
