# Generated by Django 2.1.5 on 2019-03-03 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marco_polo', '0014_auto_20190226_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('complete', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('initial_cash', models.FloatField()),
                ('end_cash', models.FloatField(default=models.FloatField())),
                ('sharpe', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=6)),
                ('buy_time', models.DateTimeField(auto_now_add=True)),
                ('sell_time', models.DateTimeField(auto_now_add=True)),
                ('buy_price', models.FloatField()),
                ('sell_price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marco_polo.Backtest')),
            ],
        ),
        migrations.CreateModel(
            name='StockInUniverse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='StockInUsedUniverse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('strategy_file', models.BinaryField()),
                ('approved', models.BooleanField(default=False)),
                ('live', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyVote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vote', models.BooleanField(default=False)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marco_polo.Strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsedUniverse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stockinuseduniverse',
            name='used_universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marco_polo.UsedUniverse'),
        ),
        migrations.AddField(
            model_name='stockinuniverse',
            name='universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marco_polo.Universe'),
        ),
        migrations.AddField(
            model_name='backtest',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marco_polo.Strategy'),
        ),
        migrations.AddField(
            model_name='backtest',
            name='universe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='universe', to='marco_polo.UsedUniverse'),
        ),
        migrations.AddField(
            model_name='backtest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
