# Generated by Django 2.1.5 on 2019-03-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0015_auto_20190303_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='strategy_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/algos/'),
        ),
    ]
