# Generated by Django 2.1.5 on 2019-03-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0017_auto_20190306_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('exchange', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='universe',
            name='stocks',
            field=models.ManyToManyField(to='marco_polo.Stock'),
        ),
    ]
