# Generated by Django 2.1.7 on 2019-03-19 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0018_auto_20190306_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinuniverse',
            name='universe',
        ),
        migrations.RemoveField(
            model_name='stockinuseduniverse',
            name='used_universe',
        ),
        migrations.DeleteModel(
            name='StockInUniverse',
        ),
        migrations.DeleteModel(
            name='StockInUsedUniverse',
        ),
    ]
