# Generated by Django 2.1.5 on 2019-03-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0018_auto_20190306_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
