# Generated by Django 2.1.7 on 2019-03-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0019_auto_20190319_0438'),
        ('marco_polo', '0020_auto_20190323_1835'),
    ]

    operations = [
    ]
