# Generated by Django 2.1.7 on 2019-03-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0021_merge_20190324_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='useduniverse',
            name='stocks',
            field=models.ManyToManyField(related_name='used_stocks', to='marco_polo.Stock'),
        ),
    ]
