# Generated by Django 2.1.7 on 2019-03-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0022_useduniverse_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='successful',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='useduniverse',
            name='stocks',
            field=models.ManyToManyField(to='marco_polo.Stock'),
        ),
    ]
