# Generated by Django 2.1.5 on 2019-03-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0024_auto_20190328_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategyvote',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='strategyvote',
            name='user',
        ),
        migrations.AlterField(
            model_name='backtesttrade',
            name='buy_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='backtesttrade',
            name='sell_time',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='StrategyVote',
        ),
    ]
