# Generated by Django 2.1.5 on 2019-04-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0025_auto_20190330_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestvote',
            name='vote',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
