# Generated by Django 2.1.7 on 2019-04-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0025_auto_20190330_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTradeInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('live', models.BooleanField(default=True)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marco_polo.Backtest')),
            ],
        ),
    ]
