# Generated by Django 2.1.7 on 2019-04-10 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0026_livetradeinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTradeInstancePosition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open', models.BooleanField(default=False)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('qty', models.IntegerField()),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('live_trade_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marco_polo.LiveTradeInstance')),
            ],
        ),
    ]
