# Generated by Django 2.1.5 on 2019-04-15 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0026_auto_20190408_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='vote_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='backtestvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
