# Generated by Django 2.1.7 on 2019-04-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0027_livetradeinstanceposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetradeinstanceposition',
            name='symbol',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
