# Generated by Django 2.1.5 on 2019-04-16 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0028_livetradeinstanceposition_symbol'),
        ('marco_polo', '0026_auto_20190408_1759'),
    ]

    operations = [
    ]
