# Generated by Django 2.1.7 on 2019-04-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0028_livetradeinstanceposition_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='vote_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='livetradeinstance',
            name='pid',
            field=models.IntegerField(null=True),
        ),
    ]
