# Generated by Django 2.1.5 on 2019-04-20 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0030_auto_20190416_2342'),
        ('marco_polo', '0030_backtestgraph'),
    ]

    operations = [
    ]
