# Generated by Django 2.1.5 on 2019-04-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0031_merge_20190420_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetradeinstance',
            name='buying_power',
            field=models.FloatField(null=True),
        ),
    ]
