# Generated by Django 2.1.5 on 2019-04-22 21:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0031_merge_20190420_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
