# Generated by Django 2.1.5 on 2019-04-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0032_livetradeinstance_buying_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetradeinstance',
            name='starting_cash',
            field=models.FloatField(null=True),
        ),
    ]
