# Generated by Django 2.1.5 on 2019-04-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0033_livetradeinstance_starting_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetradeinstanceposition',
            name='backtest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marco_polo.Backtest'),
            preserve_default=False,
        ),
    ]
