# Generated by Django 2.1.5 on 2019-04-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0032_userprofile_reset_token'),
        ('marco_polo', '0034_livetradeinstanceposition_backtest'),
    ]

    operations = [
    ]
