# Generated by Django 2.1.5 on 2019-04-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0035_merge_20190424_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetradeinstance',
            name='pct_change_closed',
            field=models.FloatField(null=True),
        ),
    ]
