# Generated by Django 2.1.5 on 2019-04-24 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0036_livetradeinstance_pct_change_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetradeinstance',
            name='strategy',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, to='marco_polo.Strategy'),
            preserve_default=False,
        ),
    ]
