# Generated by Django 2.1.5 on 2019-04-24 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marco_polo', '0037_livetradeinstance_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetradeinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
